//ベースマップメニュー定義
var mapselectID = {
        saisinsyasin_Base: "全国最新写真(シームレス)",
        kihonzu_Base: "森林基本図",
        csrittai_Base: "CS立体図(岐阜県森林研究所)",
        keiyakubun_Base: "傾斜区分図(岐阜県森林研究所)",
        hyouzyun_Base: "国土地理院標準地図",
        tansyoku_Base: "国土地理院淡色地図",
        hakutizu_Base: "国土地理院白地図",
        sikibetu_Base: "色別標高図",
        ineikizyou_Base: "陰影起伏図",
        keisyasirokuro_Base: "傾斜量図",
        oruso_Base: "電子国土基本図(オルソ画像)",
        kutyu_Base: "空中写真(1979年頃)",
        gifukyouyu_Base: "岐阜県共有空間データ（Q地図タイル）",
        syokusei_Base: "植生図(エコリス)",
        tisitus_Base: "シームレス地質図(産総研)",
        katudansou_Base: "活断層図",
        sekisyoku_Base: "赤色立体図(10mメッシュ)",
        mieStreets_Base: "MIERUNE Streets",
        mieGray_Base: "MIERUNE Gray",
        mieDark_Base: "MIERUNE Dark",
        google_Base: "Google Maps",
        GoogleS_Base: "Google Satellite",
        GoogleSH_Base: "Google Satellite Hybrid",
        mapboxS_Base: "Mapbox Streets",
        mapboxD_Base: "Mapbox Dark",
        mapboxSL_Base: "Mapbox Satelite",
        osm_Base: "OpenStreetMap",
        esriWS_Base: "Esri World Street",
        esriWI_Base: "Esri World Imagery",
        Stamento_Base: "Stamen Toner",
        StamenT_Base: "Stamen Terrain",
        StamenW_Base: "Stamen Watercolor",
    };

//ラスターレイヤー定義    
var rasterselectID = {
        nasi_Raster: "(重ねて表示しない)",
        saisinsyasin_Raster: "＋全国最新写真(シームレス)",
        kihonzu_Raster: "＋森林基本図",
        csrittai_Raster: "＋CS立体図(岐阜県森林研究所)",
        keiyakubun_Raster: "＋傾斜区分図(岐阜県森林研究所)",
        hyouzyun_Raster: "＋国土地理院標準地図",
        tansyoku_Raster: "＋国土地理院淡色地図",
        hakutizu_Raster: "＋国土地理院白地図",
        sikibetu_Raster: "＋色別標高図",
        ineikizyou_Raster: "＋陰影起伏図",
        keisyasirokuro_Raster: "＋傾斜量図",
        oruso_Raster: "＋電子国土基本図(オルソ画像)",
        kutyu_Raster: "＋空中写真(1979年頃)",
        gifukyouyu_Raster: "＋岐阜県共有空間データ（Q地図タイル）",
        syokusei_Raster: "＋植生図(エコリス)",
        tisitus_Raster: "＋シームレス地質図(産総研)",
        katudansou_Raster: "＋活断層図",
        sekisyoku_Raster: "＋赤色立体図(10mメッシュ)",
        mieStreets_Raster: "＋MIERUNE Streets",
        mieGray_Raster: "＋MIERUNE Gray",
        mieDark_Raster: "＋MIERUNE Dark",
        google_Raster: "＋Google Maps",
        GoogleS_Raster: "＋Google Satellite",
        GoogleSH_Raster: "＋Google Satellite Hybrid",
        mapboxS_Raster: "＋Mapbox Streets",
        mapboxD_Raster: "＋Mapbox Dark",
        mapboxSL_Raster: "＋Mapbox Satelite",
        osm_Raster: "＋OpenStreetMap",
        esriWS_Raster: "＋Esri World Street",
        esriWI_Raster: "＋Esri World Imagery",
        Stamento_Raster: "＋Stamen Toner",
        StamenT_Raster: "＋Stamen Terrain",
        StamenW_Raster: "＋Stamen Watercolor",
    };
